spring.application.name=personalbudget
spring.datasource.url=jdbc:postgresql://postgres:5432/budgetsdb
spring.datasource.username=budgets_user
spring.datasource.password=Qwerty123+
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog.xml
